---
kind: pipeline
name: default
type: docker

steps:

  - name: Build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      auto_tag: true
      password:
        from_secret: docker_secret
      repo: registry.jrbit.de/tosdr/crawler.tosdr.org
      registry: registry.jrbit.de
      squash: true
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      event:
        include:
          - tag
          - push